build-binary-latest:
  stage: build
  image:
    name: golang:1.18.0-alpine3.15
  script:
    - go build -o ./weed/weed ./weed 

build-container-latest:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/docker"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.go_build"
      --destination "${CI_REGISTRY_IMAGE}:latest"