version: '2'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.go_build
    ports:
    - 9333:9333
    - 19333:19333
    command: "master -ip=master"
  volume:
    build:
      context: .
      dockerfile: Dockerfile.go_build
    ports:
    - 8080:8080
    - 18080:18080
    command: '-v=2 volume -max=5 -mserver="master:9333" -port=8080 -ip=volume'
    depends_on:
    - master
  filer:
    build:
      context: .
      dockerfile: Dockerfile.go_build
    ports:
    - 8888:8888
    - 18888:18888
    command: '-v=4 filer -master="master:9333"'
    depends_on:
    - master
    - volume
  s3:
    build:
      context: .
      dockerfile: Dockerfile.go_build
    ports:
    - 8333:8333
    command: '-v=4 s3 -filer="filer:8888"'
    depends_on:
    - master
    - volume
    - filer
