version: '2'

services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb
    ports:
      - 2135:2135
      - 8765:8765
      - 2136:2136
    environment:
      - YDB_DEFAULT_LOG_LEVEL=DEBUG
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
  server:
    image: chrislusf/seaweedfs:local
    ports:
      - 9333:9333
      - 19333:19333
      - 8084:8080
      - 18084:18080
      - 8888:8888
      - 18888:18888
    command: "server -ip=server -filer -volume.max=0 -master.volumeSizeLimitMB=1024 -volume.preStopSeconds=1"
    volumes:
      - ./master-cloud.toml:/etc/seaweedfs/master.toml
    environment:
      - WEED_LEVELDB2_ENABLED=false
      - WEED_YDB_ENABLED=true
      - WEED_YDB_DSN=grpc://ydb:2136/?database=local
      - YDB_ANONYMOUS_CREDENTIALS=1
    depends_on:
      - ydb