# This is a basic workflow to help you get started with Actions

name: tag

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Latest tag
        uses: EndBug/latest-tag@v1.4.0
        with:
          description: latest master branch builds
          tag-name: latest
