# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux # default is 
          goarch: amd64 # default is 
          goversion: 1.14 # optional, default is 
          build_flags: -tags 5BytesOffset # optional, default is 
          ldflags: -extldflags -static -X github.com/chrislusf/seaweedfs/weed/util.COMMIT=${{github.sha}}
          # Where to run `go build .`
          project_path: weed
          binary_name: weed-large-disk


